# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Resumed < Formula
  desc "Tailored resumes and cover letters built from a fact base"
  homepage "https://github.com/beetlebugorg/resumed"
  version "0.1.0-rc1"
  license "MIT"

  depends_on "typst" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/beetlebugorg/resumed/releases/download/v0.1.0-rc1/resumed_0.1.0-rc1_darwin_amd64.tar.gz"
      sha256 "0609aaae18b15ffcb7f6edec1df9c92df867e674a5911c38309991b57d20b230"

      define_method(:install) do
        bin.install "resumed"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/beetlebugorg/resumed/releases/download/v0.1.0-rc1/resumed_0.1.0-rc1_darwin_arm64.tar.gz"
      sha256 "b9d7e9df88939bc317d946827f1ad12bd1e80f03113c9bb3ef7e43e235ad8ad3"

      define_method(:install) do
        bin.install "resumed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/beetlebugorg/resumed/releases/download/v0.1.0-rc1/resumed_0.1.0-rc1_linux_amd64.tar.gz"
      sha256 "e3e721cef5ed8f7b6322511e0cf3fffa96e13ba725a947eaacf7df654d11134a"
      define_method(:install) do
        bin.install "resumed"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/beetlebugorg/resumed/releases/download/v0.1.0-rc1/resumed_0.1.0-rc1_linux_arm64.tar.gz"
      sha256 "fa9741e1a1c0bf4bcc232e707a38506574320b4ce518734a816a0ff94278bb16"
      define_method(:install) do
        bin.install "resumed"
      end
    end
  end

  test do
    system "#{bin}/resumed", "help"
  end
end
