# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Resumed < Formula
  desc "Tailored resumes and cover letters built from a fact base"
  homepage "https://github.com/beetlebugorg/resumed"
  version "0.1.0"
  license "MIT"

  depends_on "typst"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/beetlebugorg/resumed/releases/download/v0.1.0/resumed_0.1.0_darwin_amd64.tar.gz"
      sha256 "ec9da97b75527bcaad4cf2c7fa8e82962e7294969a6ee4fb69821cae63f169ee"

      define_method(:install) do
        bin.install "resumed"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/beetlebugorg/resumed/releases/download/v0.1.0/resumed_0.1.0_darwin_arm64.tar.gz"
      sha256 "5e03d06dc5006136ac72e66bd0d1357e49766b8807c77ec3165ce99a06748e5c"

      define_method(:install) do
        bin.install "resumed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/beetlebugorg/resumed/releases/download/v0.1.0/resumed_0.1.0_linux_amd64.tar.gz"
      sha256 "2eb14749507e0a307302b17ce044ba9fa81c9a7f804d5ea89274027723ced1b4"
      define_method(:install) do
        bin.install "resumed"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/beetlebugorg/resumed/releases/download/v0.1.0/resumed_0.1.0_linux_arm64.tar.gz"
      sha256 "704d3110d03d94cb75741954c6b08cae4a248eda4d6c5095b62e789f888703f3"
      define_method(:install) do
        bin.install "resumed"
      end
    end
  end

  test do
    system "#{bin}/resumed", "help"
  end
end
